import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Wrapping the body with AuthProvider component for accessing session using useSession hook.*/}
     <AuthProvider>
     <body style={{backgroundColor : 'black'}} className={inter.className}>{children}</body>
     </AuthProvider>
    </html>
  );
}
